### ISSUE TITLE
修改密码

### ISSUE THREAD

**Issue by yuzhi-jiang** [dqzboy/proxyui#1]
我按照规则生成的各种密码, 过了前端校验,但是后端校验依然不过
Password must be 8-16 characters long and contain at least one letter and one number
![image](https://github.com/user-attachments/assets/14e7cc81-f5f8-46cd-b00d-27ad1cc071ac)
![image](https://github.com/user-attachments/assets/b0031707-8f23-458f-86a5-a81f54f64aab)

**Comment by dqzboy** [comment]
新版本是8-16字符 加特殊字符

**Comment by yuzhi-jiang** [comment]
按照图中,生成的似乎符合规则 [8-16字符 加特殊字符]

**Comment by dqzboy** [comment]
咋部署的？

**Comment by yuzhi-jiang** [comment]
Docker-Proxy中有个是部署 hubcmd-ui
![image](https://github.com/user-attachments/assets/2ac66751-8c7c-468a-b149-996d6b2e5a4b)

**Comment by dqzboy** [comment]
稍等，我看看能不能复现出来

**Comment by dqzboy** [comment]
稍等 好像之前构建的docker镜像是旧版

**Comment by yuzhi-jiang** [comment]
好的,需要我手动run吗,还是重新脚本安装那个服务

**Comment by dqzboy** [comment]
先不要安装呢，我处理下

**Comment by yuzhi-jiang** [comment]
好的,处理好了吗

**Comment by dqzboy** [comment]
暂时没有时间处理呢，先不要部署

**Comment by yuzhi-jiang** [comment]
好的

**Comment by dqzboy** [comment]
已修复https://github.com/dqzboy/Docker-Proxy/commit/8c7be1018700663ac061c9ead80595ed2452af80

此仓库不是Docker-Proxy项目仓库，后期提交issues到[Docker-Proxy](https://github.com/dqzboy/Docker-Proxy)
